// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_DropZone.cpp"
#include "6YEA5652QU/moc_MainWindow.cpp"
#include "6YEA5652QU/moc_ResultPanel.cpp"
#include "6YEA5652QU/moc_SpinnerWidget.cpp"
